POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1ZDRiMWM1OWNlNjc4MDkwOTlmMzYxNCIsImlhdCI6MTcwODQ0Njk2M30.VE0YaEpManODUllcwYjcV52YpKDLf_NzzcKyrHCHrPk

{
    "title": "First Blog",
    "author": "Mrs. X",
    "url": "http://first-blog.com",
    "likes": 16,
    "user": "65d4b1c59ce67809099f3614"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB5eWtrb28xIiwiaWQiOiI2NWQ0YjI0NDljZTY3ODA5MDk5ZjM2MWEiLCJpYXQiOjE3MDg0NDY3OTd9.xg7arh17bVvkTxsrjpD4OKh8YsSZebfz9loyqzPJyik

{
    "title": "Second Blog",
    "author": "Mrs. X",
    "url": "http://second-blog.com",
    "likes": 3,
    "user": "65d4b2449ce67809099f361a"
}

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "pyykkoo1",
    "name": "Oskari",
    "password": "secrettt"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "pyykkoo1",
    "password": "secrettt"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}